version: '3.1'

services:
  angel_mr: 
    image: 'postgres:16.3'
    container_name: angel_mr
    restart: always
    environment:
      POSTGRES_DB: angelmrdb
      POSTGRES_USER: angel
      POSTGRES_PASSWORD: pato12345
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432